set dot_mark=.
set copyright=Copyright (C) 2015-2021 Hikari Calyx Tech. All Rights Reserved.
set t0000=Unlock Utility 2
set t0001=Power off the phone and connect it to PC.
set t0002=Device connected.
set t0003=Please input encoding message you got from HCTSW Care: 
set t0004=Initializing Unlock...If it freezes for more than 2 minutes, please contact HCTSW.
set t0005=Your bootloader type is
set t0006=Security Version:
set t0007=Flashing service bootloader...
set t0008=Unlocking bootloader...
set t0009=Please look at your phone. Use volume key to choose UNLOCK THE BOOTLOADER, and power key to confirm.
set t0010=DO NOT DISCONNECT YOUR PHONE TO PC DURING THE PROCEDURE.
set t0011=Waiting for the phone finishing erasing...
set t0012=All done!
set t0013=ERROR: Your eMMC is damaged. Flash cannot proceed.
set t0014=ERROR: Your phone already has unlocked bootloader.
set t0015a=Usage:
set t0015b=[parameter]
set t0016=You can only use at most one parameter.
set t0017=Parameters:
set t0018= No Parameters  : Use this tool directly.
set t0019= -v, --verbose  : Enter verbose mode.
set t0020= -?, -h, --help : Show this help.
set t0021=Project Code:
set t0022=DM-Veracity Challenge:
set t0023=Challenge Passed. 
set t0024=Brand Code: 
set t0025=UID:
set t0026a=Your device
set t0026b=has connected.
set t0029=Please input elevation server address you got from HCTSW Care: 
set t0030=
set t0031=
set t0032=WARNING: Obsoleted OS detected. HCTSW Care recommends you to update to Windows 10.
set t0033=ERROR: Challenge cannot be passed. Press any key to reboot the phone and try again.
set t0034=Waiting for phone reboot...
set t0035=========== PLEASE COPY CONTENT BELOW TO HCTSW CARE ==========
set t0036=========== PLEASE COPY CONTENT ABOVE TO HCTSW CARE ==========